<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
$_code=$this->getMethodCode();
?>

    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
         <li>
            <a id="more_info_<?php echo $_code; ?>" href="https://www.itau.com.br/empresas/recebimentos/shopline/" target="_blank"><?php echo __('More information about Itaú Shopline') ?></a>
        </li>
    </ul>

<div>
</div>